version: 2

sources:
  - name: source_table
    schema: "staging"
    quoting:
      database: false
      schema: false
      identifier: false
    loader: stitch
    tables:
      - name: source_campaign
      - name: source_briefing
      - name: source_global_design

# models:
#   - name: trans_join
#     columns:
#       - name: creative_id
#         tests:
#           - non-null